language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: ONE_TIME_TESTS=true
      services:
        - docker
      addons:
        apt:
          packages:
            - doxygen

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo mkdir -p /etc/docker && echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json && sudo service docker restart; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ci/build-docker-image.sh docker/ci/Dockerfile bananocoin/banano; fi

script:
  - echo "BANANO"

deploy:
  provider: script
  skip_cleanup: true
  script: ci/deploy-docker.sh
  on:
    all_branches: true
    condition: -n "$ONE_TIME_TESTS"
